import Head from "next/head"
import Footer from "../components/Footer"
import Header from "../components/Header"
import Main from "../components/Main"

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="overflow-hidden p-5">
        <Header />
        <Main />
      </main>
      <Footer />
    </div>
  )
}

export default Home
